spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timefold?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: dev
    password: devpw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.maximum-pool-size: 20
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
